language: python
sudo: false
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install flake8 codecov

install:
  - pip install .
  - pip install PyOpenSSL pyasn1 cryptography

script:
  - flake8 --ignore=E501 --exclude=__init__.py .
  - pushd /tmp && python -c 'import pypinksign' && popd
  - pytest

after_success:
  - codecov # submit coverage
