version: 2.1


jobs:
  build-and-test-39: &template
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          command: pip install .
          name: python/install-deps
      - run:
          command: pip install -U flake8 codecov
          name: Install tools
      - run:
          command: coverage run pypinksign/test_pinkSign.py
          name: Test
  build-and-test-38:
    <<: *template
    docker:
      - image: circleci/python:3.8
  build-and-test-37:
    <<: *template
    docker:
      - image: circleci/python:3.7
  build-and-test-36:
    <<: *template
    docker:
      - image: circleci/python:3.6
workflows:
  main:
    jobs:
      - build-and-test-39
      - build-and-test-38
      - build-and-test-37
      - build-and-test-36
